name: pytest

on:
  push:
    branches:
     - master
    tags-ignore:
      - '**'
  pull_request:

jobs:
  tests:
    name: "Python ${{ matrix.py }} on OS ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        py: ["3.7", "3.9", "3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v3"

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install development version
        run: |
          pip install -v .

      - name: Install extra test dependencies
        run: |
          pip install .[test_extra]

      - name: Run pytest default tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title: 'Test Report'

      - name: Install Dev Dependencies
        run: |
          pip install .[dev]

      - name: Run pytest Dev Tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title: 'Dev Test Report'
          pytest-args: '-m dev'